# Generated by Django 6.0.2 on 2026-03-03 14:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0002_alter_profile_options_profile_sex'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='agreed',
            field=models.BooleanField(default=True, verbose_name='Соглашение про отправку уведомлений на почту'),
        ),
    ]
